Repository qiboteam/qibocal, pull requests merged in 2022-12, with the labels that each got.

#170 Fix typos
  doc/source/getting-started/interface.rst
Labels: documentation

#172 Fixing windows installation
  poetry.lock
  pyproject.toml
Labels: enhancement

#178 Fixing tests failing on MacOS
  poetry.lock
  pyproject.toml
Labels: bug

#156 added web visualization of multiple data reports
  runcards/actions_qq_5q.yml
  src/qibocal/calibrations/characterization/qubit_spectroscopy.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy.py
  src/qibocal/web/app.py
  src/qibocal/web/server.py
  src/qibocal/web/templates/template.html
Labels: enhancement

#164 Passing list of qubits for each calibration routines
  src/qibocal/calibrations/characterization/allXY.py
  src/qibocal/calibrations/characterization/calibrate_qubit_states.py
  src/qibocal/calibrations/characterization/flipping.py
  src/qibocal/calibrations/characterization/multi_t1.py
  src/qibocal/calibrations/characterization/qubit_spectroscopy.py
  src/qibocal/calibrations/characterization/rabi_oscillations.py
  src/qibocal/calibrations/characterization/ramsey.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy.py
  src/qibocal/calibrations/characterization/t1.py
  src/qibocal/cli/builders.py
  src/qibocal/data.py
  src/qibocal/fitting/methods.py
  src/qibocal/plots/allXY.py
  src/qibocal/plots/calibrate_qubit_states.py
  src/qibocal/plots/flipping.py
  src/qibocal/plots/rabi.py
  src/qibocal/plots/ramsey.py
  src/qibocal/plots/spectroscopies.py
  src/qibocal/plots/t1.py
Labels: enhancement, urgent

#134 Calibration docs
  .pre-commit-config.yaml
  doc/source/api-reference/qibocal.rst
  doc/source/getting-started/example.rst
  doc/source/getting-started/index.rst
  doc/source/getting-started/installation.rst
  doc/source/getting-started/interface.rst
  doc/source/getting-started/qq-live_screenshot.png
  doc/source/getting-started/resonator_spectr_qqlive.png
  doc/source/index.rst
  src/qibocal/calibrations/characterization/allXY.py
  src/qibocal/calibrations/characterization/calibrate_qubit_states.py
  src/qibocal/calibrations/characterization/flipping.py
  src/qibocal/calibrations/characterization/qubit_spectroscopy.py
  src/qibocal/calibrations/characterization/rabi_oscillations.py
  src/qibocal/calibrations/characterization/ramsey.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy.py
  src/qibocal/calibrations/characterization/t1.py
  src/qibocal/plots/heatmaps.py
  src/qibocal/plots/scatters.py
Labels: documentation, calibration

#183 Add platform runcard in qq runcard
  runcards/actions_qq_1q.yml
  src/qibocal/cli/_base.py
  src/qibocal/cli/builders.py
Labels: enhancement

#188 New docs font and version display
  doc/source/conf.py
  doc/source/index.rst
Labels: documentation

#190 Back to furo font
  doc/source/conf.py
Labels: documentation

#184 Publishing workflow
  .github/workflows/publish.yml
  doc/source/conf.py
  poetry.lock
  pyproject.toml
Labels: documentation
