Repository qiboteam/qibocal, pull requests merged in 2023-11, with the labels that each got.

#595 Add platform and backend entries to qq commands
  poetry.lock
  runcards/monitor.yml
  src/qibocal/auto/runcard.py
  src/qibocal/cli/_base.py
  src/qibocal/cli/acquisition.py
  src/qibocal/cli/autocalibration.py
  src/qibocal/cli/fit.py
  src/qibocal/cli/report.py
  src/qibocal/cli/utils.py
  src/qibocal/protocols/characterization/readout_characterization.py
  tests/runcards/protocols.yml
  tests/test_cli_utils.py
  tests/test_protocols.py
Labels: enhancement

#602 Fix update in readout optimization protocols
  src/qibocal/protocols/characterization/readout_optimization/resonator_amplitude.py
  src/qibocal/protocols/characterization/readout_optimization/resonator_frequency.py
  src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency.py
  src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_power.py
  src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power.py
Labels: bug

#621 msr->signal in runcards
  runcards/monitor.yml
  src/qibocal/protocols/characterization/flux_dependence/qubit_flux_tracking.py
Labels: bug

#605 Avoided crossing
  src/qibocal/auto/operation.py
  src/qibocal/protocols/characterization/__init__.py
  src/qibocal/protocols/characterization/flux_dependence/avoided_crossing.py
  src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
  tests/runcards/protocols.yml
Labels: two qubit gates

#575 Add documentation resonator spectroscopy experiment
  doc/source/conf.py
  doc/source/getting-started/protocols.rst
  doc/source/protocols/index.rst
  doc/source/protocols/resonator_spectroscopy.rst
  doc/source/protocols/resonator_spectroscopy_high.png
  doc/source/protocols/resonator_spectroscopy_low.png
  doc/source/refs.bib
Labels: documentation

#617 Implementing validation using Chi squared
  doc/source/getting-started/index.rst
  doc/source/getting-started/validation.rst
  src/qibocal/auto/execute.py
  src/qibocal/auto/runcard.py
  src/qibocal/auto/status.py
  src/qibocal/auto/task.py
  src/qibocal/auto/validation.py
  src/qibocal/auto/validators/__init__.py
  src/qibocal/auto/validators/chi2.py
  src/qibocal/protocols/characterization/coherence/spin_echo.py
  src/qibocal/protocols/characterization/coherence/t1.py
  src/qibocal/protocols/characterization/coherence/t2.py
  src/qibocal/protocols/characterization/coherence/zeno.py
  src/qibocal/protocols/characterization/ramsey.py
  tests/runcards/chi_squared.yml
  tests/test_protocols.py
  tests/test_validators.py
Labels: exceptional flow

#638 Remove extra dependencies for RTD
  poetry.lock
  pyproject.toml
Labels: dependencies

#642 Fixing punchout plots
  src/qibocal/protocols/characterization/resonator_punchout.py
  src/qibocal/protocols/characterization/resonator_punchout_attenuation.py
Labels: bug

#647 Fix dispersive shift plot
  src/qibocal/protocols/characterization/dispersive_shift.py
Labels: bug
