Repository qiboteam/qibocal, pull requests merged in 2023-07, with the labels that each got.

#432 Fix dispersive shift updated frequency
  src/qibocal/protocols/characterization/dispersive_shift.py
Labels: bug

#438 Dump report after each protocol
  src/qibocal/auto/execute.py
  src/qibocal/cli/_base.py
  src/qibocal/cli/builders.py
  src/qibocal/protocols/characterization/ramsey.py
  src/qibocal/protocols/characterization/resonator_spectroscopy.py
  src/qibocal/protocols/characterization/utils.py
  tests/test_auto.py
  tests/test_task_options.py
Labels: enhancement

#437 adapting flux routines fitting to the latest version of qibocal
  src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/utils.py
  tests/runcards/protocols.yml
Labels: enhancement, calibration

#442 Adding logs
  src/qibocal/auto/execute.py
  src/qibocal/auto/operation.py
  src/qibocal/auto/task.py
  src/qibocal/cli/builders.py
  src/qibocal/config.py
Labels: enhancement
