Repository qiboteam/qibocal, pull requests merged in 2023-09, with the labels that each got.

#482 Fix problems with Rabi fitting
  src/qibocal/protocols/characterization/rabi/amplitude.py
  src/qibocal/protocols/characterization/rabi/length.py
  src/qibocal/protocols/characterization/ramsey.py
Labels: bug

#462 Implement flux crosstalk matrix
  src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/utils.py
  tests/runcards/protocols.yml
Labels: enhancement

#485 Initial refactor of the documentation
  doc/source/api-reference/index.rst
  doc/source/api-reference/qibocal.rst
  doc/source/developer-guides/general.rst
  doc/source/developer-guides/index.rst
  doc/source/developer-guides/new_protocol.rst
  doc/source/developer-guides/output.png
  doc/source/getting-started/Qibocal.png
  doc/source/getting-started/example.rst
  doc/source/getting-started/index.rst
  doc/source/getting-started/installation.rst
  doc/source/getting-started/interface.rst
  doc/source/getting-started/protocols.rst
  doc/source/getting-started/qpu_characterization.svg
  doc/source/getting-started/qq-live_screenshot.png
  doc/source/getting-started/qq_qibocal.svg
  doc/source/getting-started/resonator_sample/resonator_spectroscopy_sample.rst
  doc/source/getting-started/resonator_spectr_qqlive.png
  doc/source/getting-started/runcard.rst
Labels: documentation

#486 Adjusting flux spectroscopy report
  src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/utils.py
Labels: bug

#526 Include update methods in all protocols
  src/qibocal/auto/execute.py
  src/qibocal/auto/operation.py
  src/qibocal/auto/task.py
  src/qibocal/fitting/classifier/run.py
  src/qibocal/protocols/characterization/allxy/drag_pulse_tuning.py
  src/qibocal/protocols/characterization/classification.py
  src/qibocal/protocols/characterization/coherence/spin_echo.py
  src/qibocal/protocols/characterization/coherence/t1.py
  src/qibocal/protocols/characterization/coherence/t1_sequences.py
  src/qibocal/protocols/characterization/coherence/t2.py
  src/qibocal/protocols/characterization/coherence/t2_sequences.py
  src/qibocal/protocols/characterization/coherence/zeno.py
  src/qibocal/protocols/characterization/dispersive_shift.py
  src/qibocal/protocols/characterization/flipping.py
  src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
  src/qibocal/protocols/characterization/qubit_spectroscopy.py
  src/qibocal/protocols/characterization/rabi/amplitude.py
  src/qibocal/protocols/characterization/rabi/length.py
  src/qibocal/protocols/characterization/rabi/length_sequences.py
  src/qibocal/protocols/characterization/ramsey.py
  src/qibocal/protocols/characterization/ramsey_sequences.py
  src/qibocal/protocols/characterization/readout_optimization/resonator_frequency.py
  src/qibocal/protocols/characterization/resonator_punchout.py
  src/qibocal/protocols/characterization/resonator_punchout_attenuation.py
  src/qibocal/protocols/characterization/resonator_spectroscopy.py
  src/qibocal/protocols/characterization/resonator_spectroscopy_attenuation.py
  src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
  src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
  src/qibocal/update.py
  tests/test_update.py
Labels: enhancement
