Repository qiboteam/qibocal, pull requests merged in 2023-10, with the labels that each got.

#536 Fix update not working using `qq fit`
  src/qibocal/auto/task.py
  src/qibocal/cli/fit.py
  src/qibocal/cli/report.py
  tests/test_auto.py
  tests/test_task_options.py
Labels: bug

#532 ramsey error with probabilities
  src/qibocal/auto/operation.py
  src/qibocal/protocols/characterization/ramsey.py
  src/qibocal/protocols/characterization/ramsey_sequences.py
  src/qibocal/protocols/characterization/utils.py
  tests/runcards/protocols.yml
  tests/test_utils.py
Labels: deploy on hardware

#548 Add fidelity to classification
  src/qibocal/protocols/characterization/classification.py
  src/qibocal/update.py
  tests/test_update.py
Labels: bug

#557 Implement update for twpa optimization protocols
  src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency.py
  src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power.py
  src/qibocal/update.py
  tests/test_update.py
Labels: enhancement

#569 Minor fixes for some protocols
  src/qibocal/cli/acquisition.py
  src/qibocal/cli/autocalibration.py
  src/qibocal/protocols/characterization/coherence/t2.py
  src/qibocal/protocols/characterization/coherence/utils.py
  src/qibocal/protocols/characterization/dispersive_shift.py
  src/qibocal/protocols/characterization/ramsey.py
Labels: bug

#539 Add protocol for calibration of pulse to generate state 2
  src/qibocal/protocols/characterization/__init__.py
  src/qibocal/protocols/characterization/allxy/allxy.py
  src/qibocal/protocols/characterization/qubit_spectroscopy_ef.py
  src/qibocal/protocols/characterization/rabi/ef.py
  src/qibocal/protocols/characterization/rabi/utils.py
  src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
  src/qibocal/update.py
  tests/runcards/protocols.yml
  tests/test_update.py
Labels: enhancement

#577 Adding tutorial on Qibocal API in documentation
  doc/source/getting-started/interface.rst
  doc/source/tutorials/api.rst
  doc/source/tutorials/classification_plot.png
  doc/source/tutorials/classification_table.png
  doc/source/tutorials/index.rst
Labels: documentation

#579 Reducing import overhead
  src/qibocal/fitting/classifier/qubit_fit.py
  src/qibocal/fitting/classifier/run.py
  tests/test_auto.py
  tests/test_classifiers.py
  tests/test_protocols.py
  tests/test_task_options.py
Labels: bug

#591 fix chevron for no couplers
  src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
Labels: bug
