Repository qiboteam/qibocal, pull requests merged in 2023-03, with the labels that each got.

#243 optimizing data agroupation with numpy arrays
  runcards/actions_qq_1q.yml
  src/qibocal/cli/builders.py
  src/qibocal/plots/allXY.py
  src/qibocal/plots/calibrate_qubit_states.py
  src/qibocal/plots/flipping.py
  src/qibocal/plots/rabi.py
  src/qibocal/plots/ramsey.py
  src/qibocal/plots/spectroscopies.py
  src/qibocal/plots/spin_echo.py
  src/qibocal/plots/t1.py
  src/qibocal/plots/utils.py
  src/qibocal/web/app.py
  src/qibocal/web/report.py
  src/qibocal/web/templates/template.html
Labels: enhancement

#269 Fix bugs related to plotting
  src/qibocal/calibrations/characterization/ramsey.py
  src/qibocal/calibrations/characterization/t1.py
  src/qibocal/cli/builders.py
  src/qibocal/fitting/methods.py
  src/qibocal/plots/allXY.py
  src/qibocal/plots/flipping.py
  src/qibocal/plots/rabi.py
  src/qibocal/plots/ramsey.py
  src/qibocal/plots/spectroscopies.py
  src/qibocal/plots/spin_echo.py
  src/qibocal/plots/t1.py
Labels: bug

#237 Automated runner: normal flow
  .github/workflows/deploy.yml
  .github/workflows/tests.yml
  doc/source/getting-started/autoruncard.rst
  doc/source/getting-started/index.rst
  poetry.lock
  pyproject.toml
  src/qibocal/auto/__init__.py
  src/qibocal/auto/draw.py
  src/qibocal/auto/execute.py
  src/qibocal/auto/graph.py
  src/qibocal/auto/history.py
  src/qibocal/auto/operation.py
  src/qibocal/auto/runcard.py
  src/qibocal/auto/status.py
  src/qibocal/auto/task.py
  src/qibocal/auto/validate.py
  tests/runcards/autocalibration.yaml
  tests/runcards/diamond.yaml
  tests/runcards/horizontal.yaml
  tests/runcards/multi-horizontal.yaml
  tests/runcards/tree.yaml
  tests/runcards/vertical.yaml
  tests/test_auto.py
Labels: enhancement

#270 Removing precision sweep
  runcards/actions_qq_1q.yml
  runcards/actions_qq_5q.yml
  runcards/dummy.yml
  src/qibocal/calibrations/characterization/qubit_spectroscopy.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy.py
  src/qibocal/fitting/methods.py
  src/qibocal/plots/spectroscopies.py
  tests/test_fitting_methods.py
Labels: enhancement

#195 Routines using hardware sweepers
  runcards/actions_qm.yml
  runcards/actions_qq_1q.yml
  runcards/actions_qq_5q.yml
  runcards/sweepers_qblox.yml
  src/qibocal/calibrations/__init__.py
  src/qibocal/calibrations/characterization/allXY.py
  src/qibocal/calibrations/characterization/calibrate_qubit_states.py
  src/qibocal/calibrations/characterization/chevron.py
  src/qibocal/calibrations/characterization/cryoscope.py
  src/qibocal/calibrations/characterization/flipping.py
  src/qibocal/calibrations/characterization/qubit_spectroscopy.py
  src/qibocal/calibrations/characterization/rabi.py
  src/qibocal/calibrations/characterization/ramsey.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy.py
  src/qibocal/calibrations/characterization/t1.py
  src/qibocal/plots/__init__.py
  src/qibocal/plots/chevron.py
  src/qibocal/plots/cryoscope.py
  src/qibocal/plots/spectroscopies.py
Labels: calibration

#295 replace ro_pulses[qubit].frequency with ro_pulse.frequency
  src/qibocal/calibrations/characterization/resonator_spectroscopy.py
Labels: bug
