Repository qiboteam/qibocal, pull requests merged in 2023-06, with the labels that each got.

#366 Add possibility to disable and customize update mechanism
  src/qibocal/auto/execute.py
  src/qibocal/cli/_base.py
  src/qibocal/cli/auto_builder.py
  src/qibocal/cli/builders.py
  src/qibocal/protocols/characterization/allxy/allxy.py
  src/qibocal/protocols/characterization/allxy/allxy_drag_pulse_tuning.py
  src/qibocal/protocols/characterization/allxy/drag_pulse_tuning.py
  src/qibocal/protocols/characterization/classification.py
  src/qibocal/protocols/characterization/coherence/spin_echo.py
  src/qibocal/protocols/characterization/coherence/t1.py
  src/qibocal/protocols/characterization/coherence/t2.py
  src/qibocal/protocols/characterization/dispersive_shift.py
  src/qibocal/protocols/characterization/flipping.py
  src/qibocal/protocols/characterization/flux_depedence/qubit_flux_dependence.py
  src/qibocal/protocols/characterization/flux_depedence/resonator_flux_dependence.py
  src/qibocal/protocols/characterization/qubit_spectroscopy.py
  src/qibocal/protocols/characterization/rabi/amplitude.py
  src/qibocal/protocols/characterization/rabi/length.py
  src/qibocal/protocols/characterization/ramsey.py
  src/qibocal/protocols/characterization/resonator_punchout.py
  src/qibocal/protocols/characterization/resonator_punchout_attenuation.py
  src/qibocal/protocols/characterization/resonator_spectroscopy.py
  src/qibocal/protocols/characterization/resonator_spectroscopy_attenuation.py
  tests/runcards/test_autocalibration.yml
  tests/test_niGSC_qq.py
  tests/test_qq_auto.py
Labels: enhancement

#401 Show protocol id in tests
  tests/runcards/single_routines.yml
  tests/test_protocols.py
Labels: tests

#372 Removing pint
  poetry.lock
  pyproject.toml
  src/qibocal/auto/draw.py
  src/qibocal/auto/execute.py
  src/qibocal/auto/graph.py
  src/qibocal/auto/history.py
  src/qibocal/auto/operation.py
  src/qibocal/auto/runcard.py
  src/qibocal/auto/task.py
  src/qibocal/data.py
  src/qibocal/protocols/characterization/allxy/allxy.py
  src/qibocal/protocols/characterization/allxy/allxy_drag_pulse_tuning.py
  src/qibocal/protocols/characterization/allxy/drag_pulse_tuning.py
  src/qibocal/protocols/characterization/classification.py
  src/qibocal/protocols/characterization/coherence/spin_echo.py
  src/qibocal/protocols/characterization/coherence/t1.py
  src/qibocal/protocols/characterization/coherence/t1_sequences.py
  src/qibocal/protocols/characterization/coherence/t2.py
  src/qibocal/protocols/characterization/coherence/t2_sequences.py
  src/qibocal/protocols/characterization/coherence/utils.py
  src/qibocal/protocols/characterization/dispersive_shift.py
  src/qibocal/protocols/characterization/flipping.py
  src/qibocal/protocols/characterization/flux_depedence/qubit_flux_dependence.py
  src/qibocal/protocols/characterization/flux_depedence/resonator_flux_dependence.py
  src/qibocal/protocols/characterization/flux_depedence/utils.py
  src/qibocal/protocols/characterization/qubit_spectroscopy.py
  src/qibocal/protocols/characterization/rabi/amplitude.py
  src/qibocal/protocols/characterization/rabi/length.py
  src/qibocal/protocols/characterization/rabi/length_sequences.py
  src/qibocal/protocols/characterization/rabi/utils.py
  src/qibocal/protocols/characterization/ramsey.py
  src/qibocal/protocols/characterization/ramsey_sequences.py
  src/qibocal/protocols/characterization/randomized_benchmarking/data.py
  src/qibocal/protocols/characterization/randomized_benchmarking/fitting.py
  src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
  src/qibocal/protocols/characterization/randomized_benchmarking/utils.py
  src/qibocal/protocols/characterization/resonator_punchout.py
  src/qibocal/protocols/characterization/resonator_punchout_attenuation.py
  src/qibocal/protocols/characterization/resonator_spectroscopy.py
  src/qibocal/protocols/characterization/resonator_spectroscopy_attenuation.py
  src/qibocal/protocols/characterization/utils.py
  src/qibocal/utils.py
  tests/runcards/protocols.yml
  tests/test_auto.py
  tests/test_data.py
  tests/test_protocols.py
Labels: deploy on hardware

#373 Error bars and uncertainties for Randomized Benchmarking
  doc/source/api-reference/qibocal.rst
  doc/source/getting-started/niGSC/niGSC_and_standardrb.rst
  src/qibocal/auto/runcard.py
  src/qibocal/auto/task.py
  src/qibocal/bootstrap.py
  src/qibocal/protocols/characterization/randomized_benchmarking/fitting.py
  src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
  src/qibocal/protocols/characterization/randomized_benchmarking/utils.py
  tests/runcards/protocols.yml
  tests/test_randomized_benchmarking.py
  tests/test_task_options.py
Labels: deploy on hardware
