Repository qiboteam/qibocal, pull requests merged in 2023-05, with the labels that each got.

#308 Fix Classification Parameters closes #305
  src/qibocal/fitting/methods.py
Labels: bug

#323 Fix NIGSC tests
  src/qibocal/calibrations/niGSC/XIdrb.py
  src/qibocal/calibrations/niGSC/basics/noisemodels.py
  tests/test_niGSC_simulfilteredrb.py
  tests/test_niGSC_standardrb.py
Labels: bug

#330 Update RB examples in documentation
  doc/source/getting-started/niGSC/niGSC_and_standardrb.rst
Labels: documentation

#271 Improvements to `ActionBuilder`
  runcards/niGSC.yml
  src/qibocal/calibrations/characterization/resonator_spectroscopy.py
  src/qibocal/calibrations/niGSC/XIdrb.py
  src/qibocal/calibrations/niGSC/basics/circuitfactory.py
  src/qibocal/calibrations/niGSC/basics/experiment.py
  src/qibocal/calibrations/niGSC/basics/fitting.py
  src/qibocal/calibrations/niGSC/basics/noisemodels.py
  src/qibocal/calibrations/niGSC/basics/plot.py
  src/qibocal/calibrations/niGSC/basics/utils.py
  src/qibocal/calibrations/niGSC/simulfilteredrb.py
  src/qibocal/calibrations/niGSC/standardrb.py
  src/qibocal/cli/_base.py
  src/qibocal/cli/builders.py
  src/qibocal/cli/utils.py
  src/qibocal/web/app.py
  tests/niGSC.yml
  tests/test_fitting_methods.py
  tests/test_niGSC_circuitfactory.py
  tests/test_niGSC_experiment.py
  tests/test_niGSC_noisemodels.py
  tests/test_niGSC_qq.py
  tests/test_niGSC_simulfilteredrb.py
  tests/test_niGSC_standardrb.py
  tests/test_niGSC_xidrb.py
  tests/test_plots_utils.py
Labels: enhancement

#279 Add routines to tree executor
  poetry.lock
  pyproject.toml
  runcards/actions_qm.yml
  runcards/actions_qq.yml
  runcards/actions_qq_auto.yml
  src/qibocal/__init__.py
  src/qibocal/auto/execute.py
  src/qibocal/auto/operation.py
  src/qibocal/auto/runcard.py
  src/qibocal/auto/task.py
  src/qibocal/cli/__init__.py
  src/qibocal/cli/_base.py
  src/qibocal/cli/auto_builder.py
  src/qibocal/cli/builders.py
  src/qibocal/cli/utils.py
  src/qibocal/plots/calibrate_qubit_states.py
  src/qibocal/protocols/characterization/__init__.py
  src/qibocal/protocols/characterization/allxy/__init__.py
  src/qibocal/protocols/characterization/allxy/allxy.py
  src/qibocal/protocols/characterization/allxy/allxy_drag_pulse_tuning.py
  src/qibocal/protocols/characterization/allxy/drag_pulse_tuning.py
  src/qibocal/protocols/characterization/classification.py
  src/qibocal/protocols/characterization/coherence/__init__.py
  src/qibocal/protocols/characterization/coherence/spin_echo.py
  src/qibocal/protocols/characterization/coherence/t1.py
  src/qibocal/protocols/characterization/coherence/t2.py
  src/qibocal/protocols/characterization/coherence/utils.py
  src/qibocal/protocols/characterization/dispersive_shift.py
  src/qibocal/protocols/characterization/flipping.py
  src/qibocal/protocols/characterization/flux_depedence/__init__.py
  src/qibocal/protocols/characterization/flux_depedence/qubit_flux_dependence.py
  src/qibocal/protocols/characterization/flux_depedence/resonator_flux_dependence.py
  src/qibocal/protocols/characterization/flux_depedence/utils.py
  src/qibocal/protocols/characterization/qubit_spectroscopy.py
  src/qibocal/protocols/characterization/rabi/__init__.py
  src/qibocal/protocols/characterization/rabi/amplitude.py
  src/qibocal/protocols/characterization/rabi/length.py
  src/qibocal/protocols/characterization/rabi/utils.py
  src/qibocal/protocols/characterization/ramsey.py
  src/qibocal/protocols/characterization/resonator_punchout.py
  src/qibocal/protocols/characterization/resonator_punchout_attenuation.py
  src/qibocal/protocols/characterization/resonator_spectroscopy.py
  src/qibocal/protocols/characterization/utils.py
  src/qibocal/web/report.py
  src/qibocal/web/templates/autocalibration.html
  tests/runcards/single_routines.yml
  tests/runcards/test_autocalibration.yml
  tests/test_auto.py
  tests/test_niGSC_qq.py
  tests/test_operations.py
  tests/test_qq_auto.py
Labels: enhancement, urgent, calibration

#338 fixed allXY indentation
  src/qibocal/protocols/characterization/allxy/allxy.py
Labels: bug, urgent

#346 Fix punchout platform update
  src/qibocal/protocols/characterization/resonator_punchout.py
  src/qibocal/protocols/characterization/utils.py
Labels: bug

#331 David/res spec fix
  poetry.lock
  pyproject.toml
  src/qibocal/protocols/characterization/resonator_spectroscopy.py
  src/qibocal/protocols/characterization/utils.py
  tests/test_operations.py
Labels: bug, urgent
