Repository qiboteam/qibocal, pull requests merged in 2023-02, with the labels that each got.

#224 workflows migration
  .github/workflows/tests.yml
Labels: enhancement

#214 Live plotting refresh rate selector
  src/qibocal/cli/builders.py
  src/qibocal/plots/allXY.py
  src/qibocal/plots/calibrate_qubit_states.py
  src/qibocal/plots/flipping.py
  src/qibocal/plots/rabi.py
  src/qibocal/plots/ramsey.py
  src/qibocal/plots/spectroscopies.py
  src/qibocal/plots/spin_echo.py
  src/qibocal/plots/t1.py
  src/qibocal/web/app.py
  src/qibocal/web/templates/template.html
Labels: enhancement

#234 Fix routines for QM and Qblox
  poetry.lock
  runcards/actions_qm.yml
  runcards/sweepers_qblox.yml
  src/qibocal/calibrations/characterization/allXY.py
  src/qibocal/calibrations/characterization/qubit_spectroscopy.py
  src/qibocal/calibrations/characterization/rabi.py
  src/qibocal/calibrations/characterization/ramsey.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy_sample.py
  src/qibocal/calibrations/characterization/t1.py
  src/qibocal/fitting/methods.py
  src/qibocal/plots/spectroscopies.py
Labels: calibration

#226 Fix ramsey fit
  src/qibocal/fitting/methods.py
Labels: bug

#236 pathlib qq-compare
  src/qibocal/cli/_base.py
Labels: enhancement

#232 David/pdfreports
  src/qibocal/plots/allXY.py
  src/qibocal/plots/calibrate_qubit_states.py
  src/qibocal/plots/flipping.py
  src/qibocal/plots/rabi.py
  src/qibocal/plots/ramsey.py
  src/qibocal/plots/spectroscopies.py
  src/qibocal/plots/spin_echo.py
  src/qibocal/plots/t1.py
  src/qibocal/web/app.py
  src/qibocal/web/static/styles.css
  src/qibocal/web/templates/template.html
Labels: enhancement

#245 Dump report after each routine
  src/qibocal/calibrations/characterization/allXY.py
  src/qibocal/cli/_base.py
  src/qibocal/cli/builders.py
  src/qibocal/web/report.py
Labels: enhancement

#239 non interactive gate set characterization + action builder
  .gitignore
  doc/source/api-reference/qibocal.rst
  doc/source/conf.py
  doc/source/getting-started/index.rst
  doc/source/getting-started/niGSC/images/Example_standardRB_report.png
  doc/source/getting-started/niGSC/images/Example_standardRBerror_report.png
  doc/source/getting-started/niGSC/images/StandardRB_noerror.png
  doc/source/getting-started/niGSC/images/qibocal_niGSC.png
  doc/source/getting-started/niGSC/niGSC_and_standardrb.rst
  doc/source/getting-started/resonator_sample/resonator_spectroscopy_sample.rst
  runcards/niGSC.yml
  src/qibocal/calibrations/__init__.py
  src/qibocal/calibrations/niGSC/XIdrb.py
  src/qibocal/calibrations/niGSC/__init__.py
  src/qibocal/calibrations/niGSC/basics/__init__.py
  src/qibocal/calibrations/niGSC/basics/circuitfactory.py
  src/qibocal/calibrations/niGSC/basics/experiment.py
  src/qibocal/calibrations/niGSC/basics/fitting.py
  src/qibocal/calibrations/niGSC/basics/noisemodels.py
  src/qibocal/calibrations/niGSC/basics/plot.py
  src/qibocal/calibrations/niGSC/basics/utils.py
  src/qibocal/calibrations/niGSC/simulfilteredrb.py
  src/qibocal/calibrations/niGSC/standardrb.py
  src/qibocal/calibrations/protocols/__init__.py
  src/qibocal/calibrations/protocols/test.py
  src/qibocal/cli/builders.py
  src/qibocal/tests/niGSC.yml
  src/qibocal/tests/test_niGSC_circuitfactory.py
  src/qibocal/tests/test_niGSC_experiment.py
  src/qibocal/tests/test_niGSC_fitting.py
  src/qibocal/tests/test_niGSC_noisemodels.py
  src/qibocal/tests/test_niGSC_qq.py
  src/qibocal/tests/test_niGSC_simulfilteredrb.py
  src/qibocal/tests/test_niGSC_standardrb.py
  src/qibocal/tests/test_niGSC_xidrb.py
  src/qibocal/web/report.py
Labels: enhancement

#248 Minor fixes before release
  poetry.lock
  pyproject.toml
  runcards/actions_qq_1q.yml
  runcards/actions_qq_5q.yml
  runcards/actions_sample.yml
  runcards/dummy.yml
  runcards/simulation.yml
  src/qibocal/calibrations/characterization/qubit_spectroscopy.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy_sample.py
  src/qibocal/calibrations/niGSC/basics/plot.py
  src/qibocal/cli/builders.py
  src/qibocal/plots/spectroscopies.py
  src/qibocal/tests/test_niGSC_circuitfactory.py
Labels: enhancement

#251 Attempting to fix tests before release
  doc/source/api-reference/qibocal.rst
  src/qibocal/calibrations/niGSC/XIdrb.py
  src/qibocal/calibrations/niGSC/basics/plot.py
  src/qibocal/calibrations/niGSC/basics/utils.py
  src/qibocal/tests/test_niGSC_fitting.py
  src/qibocal/tests/test_niGSC_simulfilteredrb.py
  src/qibocal/tests/test_niGSC_standardrb.py
  src/qibocal/tests/test_niGSC_xidrb.py
Labels: urgent

#250 Upgrade pint-pandas
  doc/source/api-reference/qibocal.rst
  poetry.lock
  pyproject.toml
  src/qibocal/calibrations/niGSC/XIdrb.py
  src/qibocal/calibrations/niGSC/basics/plot.py
  src/qibocal/calibrations/niGSC/basics/utils.py
  src/qibocal/tests/test_niGSC_experiment.py
  src/qibocal/tests/test_niGSC_fitting.py
  src/qibocal/tests/test_niGSC_simulfilteredrb.py
  src/qibocal/tests/test_niGSC_standardrb.py
  src/qibocal/tests/test_niGSC_xidrb.py
Labels: urgent

#252 Add workflow for poetry deployment
  .github/workflows/deploy.yml
  .github/workflows/tests.yml
Labels: urgent
