Repository qiboteam/qibocal, pull requests merged in 2023-01, with the labels that each got.

#192 Merge pr#117 with pr#164 and additional enhancements
  runcards/actions_qq_1q.yml
  runcards/actions_qq_5q.yml
  src/qibocal/calibrations/__init__.py
  src/qibocal/calibrations/characterization/allXY.py
  src/qibocal/calibrations/characterization/calibrate_qubit_states.py
  src/qibocal/calibrations/characterization/flipping.py
  src/qibocal/calibrations/characterization/qubit_spectroscopy.py
  src/qibocal/calibrations/characterization/rabi.py
  src/qibocal/calibrations/characterization/ramsey.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy.py
  src/qibocal/calibrations/characterization/spin_echo.py
  src/qibocal/calibrations/characterization/t1.py
  src/qibocal/calibrations/characterization/utils.py
  src/qibocal/fitting/methods.py
  src/qibocal/plots/allXY.py
  src/qibocal/plots/calibrate_qubit_states.py
  src/qibocal/plots/flipping.py
  src/qibocal/plots/rabi.py
  src/qibocal/plots/ramsey.py
  src/qibocal/plots/spectroscopies.py
  src/qibocal/plots/spin_echo.py
  src/qibocal/plots/t1.py
  src/qibocal/plots/utils.py
  src/qibocal/tests/test_fitting_methods.py
  src/qibocal/web/app.py
Labels: enhancement

#194 Refactor qubit biassing port
  src/qibocal/calibrations/characterization/qubit_spectroscopy.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy.py
Labels: do not merge

#196 Fix pulse sequence creation in Rabi routines
  src/qibocal/calibrations/characterization/rabi.py
Labels: bug, urgent

#197 Fix `update_platform_runcard` method
  runcards/actions_qq_1q.yml
  src/qibocal/calibrations/characterization/qubit_spectroscopy.py
  src/qibocal/cli/builders.py
Labels: bug

#137 Adding sampling capability for resonator punchout and flux dependance
  doc/source/getting-started/index.rst
  doc/source/getting-started/resonator_sample/resonator_spectroscopy_sample.rst
  runcards/actions_sample.yml
  src/qibocal/calibrations/__init__.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy_sample.py
  src/qibocal/fitting/methods.py
  src/qibocal/fitting/utils.py
  src/qibocal/plots/spectroscopies.py
  src/qibocal/tests/test_fitting_methods.py
Labels: calibration

#200 Update Qibo version in `poetry.lock`
  poetry.lock
Labels: dependencies

#199 Fix bug with report not appearing
  src/qibocal/web/report.py
Labels: bug

#215 David/multiplotting
  src/qibocal/plots/allXY.py
  src/qibocal/plots/calibrate_qubit_states.py
  src/qibocal/plots/flipping.py
  src/qibocal/plots/rabi.py
  src/qibocal/plots/ramsey.py
  src/qibocal/plots/spectroscopies.py
  src/qibocal/plots/spin_echo.py
  src/qibocal/plots/t1.py
  src/qibocal/web/app.py
Labels: enhancement

#221 Fix allXY plot label and plot
  src/qibocal/calibrations/characterization/allXY.py
  src/qibocal/plots/allXY.py
Labels: bug

#219 Minor fix useful for multiplex
  src/qibocal/calibrations/characterization/allXY.py
  src/qibocal/calibrations/characterization/calibrate_qubit_states.py
  src/qibocal/calibrations/characterization/flipping.py
  src/qibocal/calibrations/characterization/qubit_spectroscopy.py
  src/qibocal/calibrations/characterization/rabi.py
  src/qibocal/calibrations/characterization/ramsey.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy.py
  src/qibocal/calibrations/characterization/resonator_spectroscopy_sample.py
  src/qibocal/cli/builders.py
  src/qibocal/plots/allXY.py
Labels: bug
