Repository qiboteam/qibocal, pull requests merged in 2024-01, with the labels that each got.

#690 Improve data abstraction
  src/qibocal/auto/operation.py
  src/qibocal/auto/task.py
  src/qibocal/protocols/characterization/two_qubit_interaction/chsh/protocol.py
Labels: enhancement

#644 Added documentation for resonator punchout
  doc/source/protocols/index.rst
  doc/source/protocols/resonator_punchout.rst
  doc/source/protocols/resonator_punchout_attenuation.png
  doc/source/refs.bib
Labels: documentation

#698 Updating mechanism to dump platforms
  src/qibocal/cli/acquisition.py
  src/qibocal/cli/autocalibration.py
  src/qibocal/cli/utils.py
  src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
  src/qibocal/update.py
  src/qibocal/utils.py
  tests/runcards/protocols.yml
  tests/test_update.py
Labels: require qibolab release

#679 Fix TOF routine with new sampling rate approach
  src/qibocal/cli/acquisition.py
  src/qibocal/cli/autocalibration.py
  src/qibocal/cli/utils.py
  src/qibocal/protocols/characterization/signal_experiments/time_of_flight_readout.py
  src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
  src/qibocal/update.py
  src/qibocal/utils.py
  tests/runcards/protocols.yml
  tests/test_update.py
Labels: bug

#683 Refactoring flux fits
  src/qibocal/cli/fit.py
  src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
  src/qibocal/protocols/characterization/flux_dependence/qubit_crosstalk.py
  src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/qubit_flux_tracking.py
  src/qibocal/protocols/characterization/flux_dependence/resonator_crosstalk.py
  src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/utils.py
  src/qibocal/update.py
  tests/test_protocols.py
Labels: enhancement, calibration
