Repository qiboteam/qibocal, pull requests merged in 2024-04, with the labels that each got.

#760 Fix table rendering for CZ
  src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
Labels: bug

#568 Couplers chevron
  src/qibocal/protocols/characterization/__init__.py
  src/qibocal/protocols/characterization/couplers/coupler_chevron.py
  src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
  tests/runcards/protocols.yml
  tests/runcards/protocols_couplers.yml
  tests/test_protocols.py
Labels: couplers, two qubit gates

#786 Fixing T1, T2 and T2 echo update mechanism
  src/qibocal/update.py
  tests/test_update.py
Labels: bug

#634 Add tune landscape protocol
  src/qibocal/protocols/characterization/__init__.py
  src/qibocal/protocols/characterization/couplers/coupler_chevron.py
  src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
  src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
  src/qibocal/protocols/characterization/flux_dependence/avoided_crossing.py
  src/qibocal/protocols/characterization/two_qubit_interaction/__init__.py
  src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
  src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
  src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz_signal.py
  src/qibocal/protocols/characterization/two_qubit_interaction/utils.py
  tests/runcards/protocols.yml
  tests/runcards/protocols_couplers.yml
Labels: two qubit gates

#769 Add chevron with probabilities
  src/qibocal/protocols/characterization/__init__.py
  src/qibocal/protocols/characterization/couplers/coupler_chevron.py
  src/qibocal/protocols/characterization/two_qubit_interaction/__init__.py
  src/qibocal/protocols/characterization/two_qubit_interaction/chevron/__init__.py
  src/qibocal/protocols/characterization/two_qubit_interaction/chevron/chevron.py
  src/qibocal/protocols/characterization/two_qubit_interaction/chevron/chevron_signal.py
  src/qibocal/protocols/characterization/two_qubit_interaction/chevron/utils.py
  src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
  src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz_signal.py
  tests/runcards/protocols.yml
Labels: enhancement, two qubit gates

#783 Improving binary masks for flux fitting protocols
  src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/utils.py
Labels: enhancement

#791 Fix outdated runcard
  runcards/benchmarks/routines_benchmarks.yml
Labels: bug

#689 Refactor drag pulse calibration
  src/qibocal/protocols/characterization/__init__.py
  src/qibocal/protocols/characterization/allxy/drag_pulse_tuning.py
  src/qibocal/protocols/characterization/drag.py
  tests/runcards/protocols.yml
Labels: calibration

#788 Upgrade qibolab to 0.1.6 before release
  poetry.lock
  pyproject.toml
Labels: dependencies

#684 Implement crosstalk flux matrix fit
  src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
  src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
  src/qibocal/protocols/characterization/couplers/utils.py
  src/qibocal/protocols/characterization/flux_dependence/qubit_crosstalk.py
  src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/qubit_flux_tracking.py
  src/qibocal/protocols/characterization/flux_dependence/resonator_crosstalk.py
  src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/utils.py
  src/qibocal/update.py
Labels: enhancement, calibration

#795 Show end time correctly in HTML report
  src/qibocal/cli/autocalibration.py
Labels: bug

#800 Update README
  README.md
Labels: documentation

#807 Use fft to enhance flipping fit
  src/qibocal/protocols/characterization/flipping.py
  src/qibocal/protocols/characterization/flipping_signal.py
Labels: enhancement, calibration

#808 feat: detuning for flipping
  src/qibocal/protocols/characterization/flipping.py
  src/qibocal/protocols/characterization/flipping_signal.py
  tests/runcards/protocols.yml
Labels: enhancement, calibration
