Repository qiboteam/qibocal, pull requests merged in 2024-07, with the labels that each got.

#898 Adding coupler pulse to `cz_virtualz` protocols
  src/qibocal/protocols/two_qubit_interaction/cz_virtualz.py
Labels: bug, calibration

#905 Adding `qq update` command
  doc/source/getting-started/interface.rst
  src/qibocal/auto/execute.py
  src/qibocal/auto/task.py
  src/qibocal/cli/_base.py
  src/qibocal/cli/autocalibration.py
  src/qibocal/cli/fit.py
  src/qibocal/cli/update.py
  src/qibocal/protocols/coherence/spin_echo_signal.py
  src/qibocal/protocols/coherence/t1.py
  src/qibocal/protocols/coherence/t1_signal.py
  src/qibocal/protocols/coherence/t2_signal.py
  src/qibocal/protocols/coherence/utils.py
  src/qibocal/protocols/flipping.py
  src/qibocal/protocols/flipping_signal.py
  src/qibocal/protocols/rabi/amplitude.py
  src/qibocal/protocols/rabi/amplitude_frequency.py
  src/qibocal/protocols/rabi/amplitude_frequency_signal.py
  src/qibocal/protocols/rabi/amplitude_signal.py
  src/qibocal/protocols/rabi/length.py
  src/qibocal/protocols/rabi/length_frequency.py
  src/qibocal/protocols/rabi/length_frequency_signal.py
  src/qibocal/protocols/rabi/length_signal.py
  src/qibocal/protocols/ramsey/ramsey_signal.py
  src/qibocal/protocols/randomized_benchmarking/utils.py
  src/qibocal/protocols/readout_characterization.py
  src/qibocal/protocols/resonator_spectroscopy.py
  src/qibocal/update.py
  tests/test_cli.py
  tests/test_protocols.py
  tests/test_task_options.py
Labels: enhancement

#915 Fixing fft guess
  src/qibocal/protocols/drag.py
  src/qibocal/protocols/flipping.py
  src/qibocal/protocols/flipping_signal.py
  src/qibocal/protocols/rabi/amplitude.py
  src/qibocal/protocols/rabi/amplitude_frequency.py
  src/qibocal/protocols/rabi/amplitude_frequency_signal.py
  src/qibocal/protocols/rabi/amplitude_signal.py
  src/qibocal/protocols/rabi/length.py
  src/qibocal/protocols/rabi/length_frequency.py
  src/qibocal/protocols/rabi/length_frequency_signal.py
  src/qibocal/protocols/rabi/length_signal.py
  src/qibocal/protocols/rabi/utils.py
  src/qibocal/protocols/ramsey/ramsey.py
  src/qibocal/protocols/ramsey/ramsey_signal.py
  src/qibocal/protocols/ramsey/utils.py
  src/qibocal/protocols/two_qubit_interaction/utils.py
  src/qibocal/protocols/utils.py
  tests/runcards/protocols.yml
  tests/test_executor.py
  tests/test_fft.py
Labels: bug

#927 Minor correction to qubit spectroscopy ef and drag calibration
  src/qibocal/protocols/drag.py
  src/qibocal/protocols/qubit_spectroscopy_ef.py
Labels: calibration

#869 Simplified calibration scripts
  runcards/rx_calibration.py
  runcards/script.py
  runcards/single_shot.py
  src/qibocal/__init__.py
  src/qibocal/auto/execute.py
  src/qibocal/auto/output.py
  src/qibocal/auto/task.py
  src/qibocal/cli/acquisition.py
  src/qibocal/cli/autocalibration.py
  src/qibocal/cli/report.py
  src/qibocal/web/report.py
  tests/scripts/implicit.py
  tests/scripts/simple.py
  tests/test_executor.py
  tests/test_output.py
  tests/test_task_options.py
Labels: execution

#928 Fix classifiers plot
  poetry.lock
  src/qibocal/protocols/classification.py
Labels: bug

#939 Hotfix for drag protocol
  src/qibocal/protocols/drag.py
Labels: bug, calibration

#935 Fixing report generation after upload
  src/qibocal/auto/output.py
  src/qibocal/cli/upload.py
Labels: bug

#946 Dump using `TaskId`
  src/qibocal/auto/history.py
  tests/test_protocols.py
Labels: bug

#942 Deduplicate script operations
  flake.lock
  flake.nix
  runcards/.gitignore
  runcards/rx_calibration.py
  runcards/single_shot.py
  src/qibocal/auto/execute.py
  tests/test_executor.py
Labels: execution
