Repository qiboteam/qibocal, pull requests merged in 2024-03, with the labels that each got.

#744 Solve missing plot for protocols involving chi2
  src/qibocal/protocols/characterization/coherence/spin_echo.py
  src/qibocal/protocols/characterization/coherence/spin_echo_signal.py
  src/qibocal/protocols/characterization/coherence/t1.py
  src/qibocal/protocols/characterization/coherence/t1_sequences.py
  src/qibocal/protocols/characterization/coherence/t1_signal.py
  src/qibocal/protocols/characterization/coherence/t2.py
  src/qibocal/protocols/characterization/coherence/t2_signal.py
  src/qibocal/protocols/characterization/coherence/zeno.py
  src/qibocal/protocols/characterization/coherence/zeno_signal.py
  src/qibocal/protocols/characterization/flipping.py
  src/qibocal/protocols/characterization/flipping_signal.py
  src/qibocal/protocols/characterization/qubit_spectroscopy.py
  src/qibocal/protocols/characterization/rabi/amplitude.py
  src/qibocal/protocols/characterization/rabi/amplitude_signal.py
  src/qibocal/protocols/characterization/ramsey/ramsey.py
  src/qibocal/protocols/characterization/ramsey/ramsey_signal.py
  src/qibocal/protocols/characterization/resonator_spectroscopy.py
Labels: bug

#742 Fix bug in lorentzian plot for spectroscopies
  src/qibocal/protocols/characterization/utils.py
Labels: bug

#745 Adding error message when fitting failed
  src/qibocal/cli/report.py
Labels: enhancement

#750 remove Tensorflow dependency
  poetry.lock
  pyproject.toml
  src/qibocal/fitting/classifier/nn.py
  src/qibocal/fitting/classifier/run.py
  src/qibocal/protocols/characterization/classification.py
Labels: dependencies

#754 Hotfix for rabi length following #744
  src/qibocal/protocols/characterization/rabi/length.py
  src/qibocal/protocols/characterization/rabi/length_signal.py
Labels: bug

#749 Dropping DAG
  doc/source/getting-started/autoruncard.rst
  doc/source/getting-started/example.rst
  doc/source/getting-started/index.rst
  doc/source/getting-started/runcard.rst
  doc/source/getting-started/validation.rst
  poetry.lock
  pyproject.toml
  runcards/actions_qq.yml
  runcards/monitor.yml
  src/qibocal/auto/draw.py
  src/qibocal/auto/execute.py
  src/qibocal/auto/graph.py
  src/qibocal/auto/runcard.py
  src/qibocal/auto/task.py
  src/qibocal/auto/validate.py
  src/qibocal/auto/validation.py
  src/qibocal/auto/validators/__init__.py
  src/qibocal/auto/validators/chi2.py
  src/qibocal/protocols/characterization/classification.py
  tests/runcards/autocalibration.yaml
  tests/runcards/chi_squared.yml
  tests/runcards/diamond.yaml
  tests/runcards/handlers.yml
  tests/runcards/horizontal.yaml
  tests/runcards/multi-horizontal.yaml
  tests/runcards/protocols.yml
  tests/runcards/tree.yaml
  tests/runcards/vertical.yaml
  tests/test_auto.py
  tests/test_validators.py
Labels: calibration

#763 Remove outdated keys after DAG remove
  doc/source/protocols/resonator_punchout.rst
  doc/source/protocols/resonator_spectroscopy.rst
  doc/source/tutorials/advanced.rst
  doc/source/tutorials/basic.rst
  runcards/benchmarks/routines_benchmarks.yml
  runcards/benchmarks/scaling_benchmarks.yml
  runcards/calibration_tutorial/classification.yaml
  runcards/calibration_tutorial/qubit_flux_dependence.yaml
  runcards/calibration_tutorial/qubit_spectroscopy.yaml
  runcards/calibration_tutorial/rabi.yaml
  runcards/calibration_tutorial/ramsey.yaml
  runcards/calibration_tutorial/rb.yaml
  runcards/calibration_tutorial/readout_characterization.yaml
  runcards/calibration_tutorial/resonator_punchout.yaml
  runcards/calibration_tutorial/resonator_spectroscopy_high.yaml
  runcards/calibration_tutorial/resonator_spectroscopy_low.yaml
  runcards/calibration_tutorial/t1.yaml
  runcards/monitor.yml
Labels: documentation

#752 Update qibo and qibolab dependencies
  poetry.lock
  pyproject.toml
  src/qibocal/auto/runcard.py
  tests/test_task_options.py
Labels: dependencies

#597 Changing RB data
  doc/source/tutorials/basic.rst
  runcards/actions_qq.yml
  runcards/benchmarks/scaling_benchmarks.yml
  runcards/calibration_tutorial/rb.yaml
  runcards/monitor.yml
  src/qibocal/auto/runcard.py
  src/qibocal/auto/task.py
  src/qibocal/bootstrap.py
  src/qibocal/protocols/characterization/randomized_benchmarking/circuit_tools.py
  src/qibocal/protocols/characterization/randomized_benchmarking/data.py
  src/qibocal/protocols/characterization/randomized_benchmarking/fitting.py
  src/qibocal/protocols/characterization/randomized_benchmarking/noisemodels.py
  src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
  src/qibocal/protocols/characterization/randomized_benchmarking/utils.py
  tests/runcards/protocols.yml
  tests/runcards/protocols_couplers.yml
  tests/runcards/rb_noise_protocols.yml
  tests/test_protocols.py
  tests/test_randomized_benchmarking.py
Labels: rb

#774 Specify different directory for `qq fit`
  doc/source/getting-started/interface.rst
  src/qibocal/cli/_base.py
  src/qibocal/cli/fit.py
  src/qibocal/cli/report.py
  tests/runcards/dummy_action.yml
  tests/test_cli.py
Labels: enhancement

#759 Fixing rabi issue when fitting fails
  runcards/actions_qq.yml
  src/qibocal/protocols/characterization/coherence/spin_echo.py
  src/qibocal/protocols/characterization/coherence/t1.py
  src/qibocal/protocols/characterization/coherence/t2.py
  src/qibocal/protocols/characterization/coherence/utils.py
  src/qibocal/protocols/characterization/coherence/zeno.py
  src/qibocal/protocols/characterization/qubit_spectroscopy_ef.py
  src/qibocal/protocols/characterization/rabi/amplitude.py
Labels: bug

#756 Fixing CHSH plot generation
  src/qibocal/cli/report.py
  src/qibocal/protocols/characterization/two_qubit_interaction/chsh/protocol.py
Labels: bug, two qubit gates

#691 Added possibility to sweep over flux pulses instead of bias
  poetry.lock
  src/qibocal/protocols/characterization/couplers/utils.py
  src/qibocal/protocols/characterization/flux_dependence/qubit_crosstalk.py
  src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/qubit_flux_tracking.py
  src/qibocal/protocols/characterization/flux_dependence/resonator_crosstalk.py
  src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
  src/qibocal/protocols/characterization/flux_dependence/utils.py
  tests/runcards/protocols.yml
  tests/test_protocols.py
Labels: deploy on hardware

#757 Store mitigation matrix when running CHSH
  src/qibocal/protocols/characterization/two_qubit_interaction/chsh/protocol.py
Labels: enhancement, two qubit gates

#740 Option to save single shots for coherence signal routines
  src/qibocal/protocols/characterization/coherence/spin_echo_signal.py
  src/qibocal/protocols/characterization/coherence/t1_sequences.py
  src/qibocal/protocols/characterization/coherence/t1_signal.py
  src/qibocal/protocols/characterization/coherence/t2_sequences.py
  src/qibocal/protocols/characterization/coherence/t2_signal.py
  src/qibocal/protocols/characterization/coherence/utils.py
  src/qibocal/protocols/characterization/coherence/zeno_signal.py
  tests/runcards/protocols.yml
Labels: deploy on hardware
