Repository qiboteam/qibocal, pull requests merged in 2024-02, with the labels that each got.

#668 Exceptional flow: handlers prototype
  doc/source/getting-started/validation.rst
  src/qibocal/auto/execute.py
  src/qibocal/auto/history.py
  src/qibocal/auto/runcard.py
  src/qibocal/auto/task.py
  src/qibocal/auto/validation.py
  src/qibocal/auto/validators/__init__.py
  src/qibocal/auto/validators/chi2.py
  tests/runcards/chi_squared.yml
  tests/runcards/handlers.yml
  tests/test_task_options.py
  tests/test_validators.py
Labels: exceptional flow

#665 Add singleshot unrolling
  src/qibocal/protocols/characterization/classification.py
  tests/runcards/protocols.yml
Labels: calibration

#697 fix temperature
  src/qibocal/protocols/characterization/classification.py
Labels: deploy on hardware

#664 TWPA calibration using SNR
  src/qibocal/protocols/characterization/__init__.py
  src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
  src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
  tests/runcards/protocols.yml
Labels: calibration

#666 Ramsey unrolling
  src/qibocal/protocols/characterization/ramsey.py
  src/qibocal/protocols/characterization/ramsey_signal.py
  tests/runcards/protocols.yml
Labels: calibration

#610 Sequence unrolling in standard RB
  src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
  tests/runcards/protocols.yml
Labels: rb

#582 kernels
  src/qibocal/auto/operation.py
  src/qibocal/auto/task.py
  src/qibocal/protocols/characterization/__init__.py
  src/qibocal/protocols/characterization/dispersive_shift.py
  src/qibocal/protocols/characterization/signal_experiments/calibrate_state_discrimination.py
  src/qibocal/protocols/characterization/two_qubit_interaction/chsh/protocol.py
  src/qibocal/update.py
  tests/runcards/protocols.yml
  tests/test_update.py
Labels: enhancement, calibration

#726 Restoring execution without specifying `targets` in runcard
  src/qibocal/auto/runcard.py
  src/qibocal/cli/autocalibration.py
  src/qibocal/cli/utils.py
  src/qibocal/utils.py
  tests/test_cli_utils.py
  tests/test_task_options.py
Labels: bug, urgent

#725 Adding unrolling to spin echo
  src/qibocal/protocols/characterization/__init__.py
  src/qibocal/protocols/characterization/coherence/spin_echo.py
  src/qibocal/protocols/characterization/coherence/spin_echo_signal.py
  tests/runcards/protocols.yml
Labels: enhancement, calibration

#728 Fixing platform and backend assignment through CLI
  src/qibocal/auto/runcard.py
Labels: bug, urgent

#723 Fix fitting with probabilities
  src/qibocal/protocols/characterization/__init__.py
  src/qibocal/protocols/characterization/coherence/spin_echo.py
  src/qibocal/protocols/characterization/coherence/spin_echo_signal.py
  src/qibocal/protocols/characterization/coherence/utils.py
  tests/runcards/protocols.yml
Labels: bug

#721 Refactor ramsey to use detuning instead of number of oscillations
  src/qibocal/protocols/characterization/__init__.py
  src/qibocal/protocols/characterization/ramsey/__init__.py
  src/qibocal/protocols/characterization/ramsey/ramsey.py
  src/qibocal/protocols/characterization/ramsey/ramsey_signal.py
  src/qibocal/protocols/characterization/ramsey/utils.py
  src/qibocal/protocols/characterization/ramsey_sequences.py
  tests/runcards/protocols.yml
Labels: bug
