Repository qiboteam/qibocal, pull requests merged in 2024-06, with the labels that each got.

#873 Correct bug in CHSH
  src/qibocal/protocols/two_qubit_interaction/chsh/protocol.py
Labels: bug

#871 Documentation for tof and kernels
  doc/source/protocols/index.rst
  doc/source/protocols/signal/calibrate_kernel.rst
  doc/source/protocols/signal/kernel.png
  doc/source/protocols/signal/time_of_flight.png
  doc/source/protocols/signal/time_of_flight.rst
  doc/source/protocols/signal/time_of_flight_2d.png
  doc/source/protocols/signal/time_of_flight_2d_nodem.png
Labels: documentation

#857 Rabi with frequency detuning
  .gitignore
  src/qibocal/protocols/__init__.py
  src/qibocal/protocols/rabi/amplitude.py
  src/qibocal/protocols/rabi/amplitude_frequency.py
  src/qibocal/protocols/rabi/amplitude_frequency_signal.py
  src/qibocal/protocols/rabi/amplitude_signal.py
  src/qibocal/protocols/rabi/ef.py
  src/qibocal/protocols/rabi/length.py
  src/qibocal/protocols/rabi/length_frequency.py
  src/qibocal/protocols/rabi/length_frequency_signal.py
  src/qibocal/protocols/rabi/length_sequences.py
  src/qibocal/protocols/rabi/length_signal.py
  src/qibocal/protocols/rabi/utils.py
  tests/runcards/protocols.yml
Labels: calibration

#882 Fixing T1 fit
  src/qibocal/cli/report.py
  src/qibocal/protocols/coherence/spin_echo.py
  src/qibocal/protocols/coherence/t1.py
  src/qibocal/protocols/coherence/t2.py
  src/qibocal/protocols/coherence/utils.py
  src/qibocal/protocols/coherence/zeno.py
  src/qibocal/protocols/coherence/zeno_signal.py
  tests/test_crosstalk.py
Labels: bug

#868 More docs
  doc/source/protocols/allxy.png
  doc/source/protocols/allxy.rst
  doc/source/protocols/classification.png
  doc/source/protocols/dispersive_shift.png
  doc/source/protocols/dispersive_shift.rst
  doc/source/protocols/flipping.png
  doc/source/protocols/flipping.rst
  doc/source/protocols/flipping_signal.png
  doc/source/protocols/flux/single.rst
  doc/source/protocols/index.rst
  doc/source/protocols/qubit_spectroscopy/qubit_spectroscopy.rst
  doc/source/protocols/rabi/rabi.rst
  doc/source/protocols/rabi/rabi_amplitude.png
  doc/source/protocols/rabi/rabi_ef.png
  doc/source/protocols/rabi/rabi_length.png
  doc/source/protocols/rabi/rabi_signal.png
  doc/source/protocols/rabi_amplitude.png
  doc/source/protocols/ramsey/ramsey.rst
  doc/source/protocols/signal/calibrate_kernel.rst
  doc/source/protocols/singleshot.png
  doc/source/protocols/singleshot.rst
  doc/source/protocols/t1/t1.rst
  doc/source/protocols/t2/t2.rst
  doc/source/protocols/t2_echo/t2_echo.rst
  doc/source/refs.bib
Labels: documentation

#861 Add proper protocols documentation
  doc/source/conf.py
  doc/source/getting-started/index.rst
  doc/source/getting-started/protocols.rst
  doc/source/getting-started/runcard.rst
  doc/source/protocols/allxy.png
  doc/source/protocols/allxy.rst
  doc/source/protocols/classification.png
  doc/source/protocols/dispersive_shift.png
  doc/source/protocols/dispersive_shift.rst
  doc/source/protocols/flipping.png
  doc/source/protocols/flipping.rst
  doc/source/protocols/flipping_signal.png
  doc/source/protocols/flux/crosstalk.rst
  doc/source/protocols/flux/qubit_crosstalk.png
  doc/source/protocols/flux/qubit_flux.png
  doc/source/protocols/flux/resonator_crosstalk.png
  doc/source/protocols/flux/resonator_flux.png
  doc/source/protocols/flux/single.rst
  doc/source/protocols/index.rst
  doc/source/protocols/qubit_spectroscopy/qubit_spec.png
  doc/source/protocols/qubit_spectroscopy/qubit_spectroscopy.rst
  doc/source/protocols/qubit_spectroscopy/qubit_spectroscopy_ef.png
  doc/source/protocols/rabi/rabi.rst
  doc/source/protocols/rabi/rabi_amplitude.png
  doc/source/protocols/rabi/rabi_ef.png
  doc/source/protocols/rabi/rabi_length.png
  doc/source/protocols/rabi/rabi_signal.png
  doc/source/protocols/rabi_amplitude.png
  doc/source/protocols/ramsey/ramsey.png
  doc/source/protocols/ramsey/ramsey.rst
  doc/source/protocols/ramsey/ramsey_signal.png
  doc/source/protocols/references.rst
  doc/source/protocols/resonator_punchout.rst
  doc/source/protocols/resonator_spectroscopy.rst
  doc/source/protocols/signal/calibrate_kernel.rst
  doc/source/protocols/signal/kernel.png
  doc/source/protocols/signal/time_of_flight.png
  doc/source/protocols/signal/time_of_flight.rst
  doc/source/protocols/signal/time_of_flight_2d.png
  doc/source/protocols/signal/time_of_flight_2d_nodem.png
  doc/source/protocols/singleshot.png
  doc/source/protocols/singleshot.rst
  doc/source/protocols/t1/t1.rst
  doc/source/protocols/t1/t1_prob.png
  doc/source/protocols/t1/t1_signal.png
  doc/source/protocols/t2/t2.png
  doc/source/protocols/t2/t2.rst
  doc/source/protocols/t2/t2_signal.png
  doc/source/protocols/t2_echo/t2_echo.png
  doc/source/protocols/t2_echo/t2_echo.rst
  doc/source/protocols/t2_echo/t2_echo_signal.png
  doc/source/refs.bib
  doc/source/tutorials/basic.rst
  pyproject.toml
  src/qibocal/protocols/classification.py
  src/qibocal/protocols/coherence/t2.py
  src/qibocal/protocols/coherence/t2_signal.py
  src/qibocal/protocols/qubit_spectroscopy_ef.py
  src/qibocal/protocols/ramsey/ramsey.py
  src/qibocal/protocols/ramsey/ramsey_signal.py
Labels: documentation

#904 Minor fixes to the documentation
  doc/source/protocols/flipping.rst
  doc/source/protocols/index.rst
  doc/source/protocols/qubit_spectroscopy/qubit_spectroscopy.rst
  doc/source/tutorials/advanced.rst
  doc/source/tutorials/classification_plot.png
  doc/source/tutorials/classification_table.png
  poetry.lock
  pyproject.toml
Labels: documentation
