Repository qiboteam/qibocal, pull requests merged in 2024-08, with the labels that each got.

#823 Protocol to sweep CZ amplitude
  src/qibocal/protocols/__init__.py
  src/qibocal/protocols/two_qubit_interaction/__init__.py
  src/qibocal/protocols/two_qubit_interaction/cz_sweep.py
  src/qibocal/protocols/two_qubit_interaction/cz_virtualz.py
  tests/runcards/protocols.yml
Labels: calibration, two qubit gates

#938 Generalization of two qubit protocols to iSWAP gate
  src/qibocal/protocols/__init__.py
  src/qibocal/protocols/two_qubit_interaction/__init__.py
  src/qibocal/protocols/two_qubit_interaction/chevron/chevron.py
  src/qibocal/protocols/two_qubit_interaction/chevron/chevron_signal.py
  src/qibocal/protocols/two_qubit_interaction/chevron/utils.py
  src/qibocal/protocols/two_qubit_interaction/optimize.py
  src/qibocal/protocols/two_qubit_interaction/virtual_z_phases.py
  src/qibocal/protocols/two_qubit_interaction/virtual_z_phases_signal.py
  src/qibocal/update.py
  tests/runcards/protocols.yml
  tests/test_update.py
Labels: two qubit gates

#917 Adding a proper fit of the resonance of a notch resonator
  doc/source/protocols/index.rst
  doc/source/protocols/resonator_spectroscopy.rst
  doc/source/protocols/resonator_spectroscopy/resonator_spectroscopy.rst
  doc/source/protocols/resonator_spectroscopy/resonator_spectroscopy_error_bars.png
  doc/source/protocols/resonator_spectroscopy/resonator_spectroscopy_high.png
  doc/source/protocols/resonator_spectroscopy/resonator_spectroscopy_low.png
  doc/source/protocols/resonator_spectroscopy/resonator_spectroscopy_simulation.png
  doc/source/protocols/resonator_spectroscopy/s12_fit.png
  doc/source/refs.bib
  src/qibocal/protocols/resonator_spectroscopy.py
  src/qibocal/protocols/resonator_utils.py
  src/qibocal/protocols/utils.py
  tests/runcards/protocols.yml
Labels: enhancement

#949 Executor context manager
  runcards/rx_calibration.py
  runcards/single_shot.py
  src/qibocal/auto/execute.py
  tests/test_executor.py
Labels: execution

#714 qq compare command to compare two qibocal reports
  doc/source/getting-started/interface.rst
  poetry.lock
  pyproject.toml
  src/qibocal/auto/history.py
  src/qibocal/cli/_base.py
  src/qibocal/cli/compare.py
  src/qibocal/cli/report.py
  src/qibocal/web/compared_report.py
  src/qibocal/web/report.py
  tests/runcards/dummy_compare.yml
  tests/test_cli.py
Labels: ui

#968 Hotfix for sweetspot calculation
  src/qibocal/protocols/flux_dependence/qubit_flux_dependence.py
  src/qibocal/protocols/flux_dependence/utils.py
Labels: bug
