Repository qiboteam/qibocal, pull requests merged in 2025-06, with the labels that each got.

#1168 Fix readout mitigation protocol label
  src/qibocal/protocols/readout/readout_mitigation_matrix.py
Labels: bug

#1159 Unlocking numpy `2.0.0`
  .github/workflows/tests.yml
  .github/workflows/wheels.yml
  poetry.lock
  pyproject.toml
Labels: dependencies

#1189 Minor fixes for iSWAP chevron protocol
  src/qibocal/protocols/two_qubit_interaction/chevron/chevron.py
  src/qibocal/protocols/two_qubit_interaction/chevron/utils.py
Labels: calibration

#1184 Document slurm dispatching
  .envrc
  doc/source/tutorials/connect-to-queue.bash
  doc/source/tutorials/index.rst
  doc/source/tutorials/interactive.rst
  doc/source/tutorials/ssh-remote-port.png
  flake.nix
Labels: documentation
